### ISSUE TITLE
where to get the ImageNet_LT data listed in the .txt files?

### ISSUE THREAD

**Issue by 18445864529** [dvlab-research/Parametric-Contrastive-Learning#1]
May I ask where can I download data corresponding to as listed in `ImageNet_LT_train.txt, ImageNet_LT_val.txt, ImageNet_LT_test.txt`.
I have downloaded several from the original ImageNet site but none of them corresponds to the items listed in the .txt completely.
Thanks for the answer in advance.

**Comment by jiequancui** [comment]
Hi,
The training data is just a subset of full ImageNet 2012. You can directly download the ImageNet 2012 from the official site.
