### ISSUE TITLE
Questions about center learning

### ISSUE THREAD

**Issue by zuglerQ** [dvlab-research/Parametric-Contrastive-Learning#10]
Hi, thanks for your exciting work.  
I have a question about the centre learning that I did not find any function in the paper, and I did not find any comment of centres on the code. 
Could you give any clue about how could we the parametric centres? 

I am looking forward to your reply.

**Comment by jiequancui** [comment]
Hi,

Thanks for your questions!

The center learning rebalance is described in Sec. 3.5 in our paper https://openaccess.thecvf.com/content/ICCV2021/papers/Cui_Parametric_Contrastive_Learning_ICCV_2021_paper.pdf.

The center learning is just implemented by a linear FC. Please refer to https://github.com/dvlab-research/Parametric-Contrastive-Learning/blob/main/LT/moco/builder.py #44

Best,
Jiequan
