### ISSUE TITLE
Question about supcon framework

### ISSUE THREAD

**Issue by thomascong121** [dvlab-research/Parametric-Contrastive-Learning#11]
Hi, thanks for the great work, I have a question about the selection of the framework. Since you use the supervised contrastive loss, why not use the framework from [supcon](https://arxiv.org/pdf/2004.11362.pdf) and use MoCo framework instead?

**Comment by jiequancui** [comment]
Hi,

Thanks for your question.
In the original paper of Supcon, it needs a large batch size and GPU memory while the MoCo framework is more friendly with respect to GPU resources.
