### ISSUE TITLE
The meaning of beta and gamma in the code

### ISSUE THREAD

**Issue by madoka109** [dvlab-research/Parametric-Contrastive-Learning#12]
parser.add_argument('--beta', default=1.0, type=float,
                    help='supervise loss weight')
parser.add_argument('--gamma', default=1.0, type=float,
                    help='paco loss')
I found these two parameters in the code, and they are used in losses.py, but I can't understand the using of them, are they mentioned in the paper?
If you can explain them to me, I will very appreciate on you, thank you!

**Comment by jiequancui** [comment]
Hi,

Thanks for your question.

Please ignore the beta and gamma hyper-parameters. They are set to 1.0 in our all experiments.

The only meaningful hyper-parameter of paco loss is alpha which is described in our paper.

**Comment by madoka109** [comment]
![image](https://user-images.githubusercontent.com/79368885/155530605-a58bea46-3fb9-4462-9ff0-7e2f216aa966.png)

Thanks for your reply!
Besides, I have another question about c_y in above formula. What does c_y specifically mean?

**Comment by jiequancui** [comment]
Hi,

The c_y is a learnable sample for class y. The learnable samples are implemented with a linear fc weights.

**Comment by madoka109** [comment]
I understand, Thanks!
