### ISSUE TITLE
Different resnet backbones

### ISSUE THREAD

**Issue by thomascong121** [dvlab-research/Parametric-Contrastive-Learning#14]
Hi thanks for the great work. I notice that you have used different renet backbones for cifar training (load from resnet_cifar) and imagenet training (load from resnet_imagenet). Is there a reason why you use different backbones?

**Comment by jiequancui** [comment]
Hi,

Thanks for your question.
For fair comparisons with previous work, we just follow the community tradition.

Best,

**Comment by thomascong121** [comment]
Alright, thanks for the response. Again, I think this is a great work that should deserve much higher citations. :)
