### ISSUE TITLE
The checkpoint on iNat2018

### ISSUE THREAD

**Issue by Duconnor** [dvlab-research/Parametric-Contrastive-Learning#15]
Thank you guys for your impressive work and releasing the code. I just wonder when will the checkpoint on iNat2018 be released? I'm looking forward to that. Thanks a lot!

**Comment by jiequancui** [comment]
Hi, thanks for your interest in our work.

We have already released the log file for checking. 
If you met problems with reproduction, welcome to discuss them with me.

We are being dedicated to an improved version of PaCo. It will take some time to re-train it and release the models.

**Comment by Duconnor** [comment]
Thanks for your quick reply, I've successfully reproduce the result. But I do think there is one tiny bug here https://github.com/dvlab-research/Parametric-Contrastive-Learning/blob/4609959c490a90698e379720e1a9d4a01edd94ac/LT/paco_lt.py#L530
which I think should be changed to 
`total_logits = torch.empty((0, args.num_classes)).cuda() `

**Comment by jiequancui** [comment]
Thanks for your suggestion. 

I will fix the issue.
