### ISSUE TITLE
Looking forward to the code for "Region Rebalance for Long-Tailed Semantic Segmentation"

### ISSUE THREAD

**Issue by bowenroom** [dvlab-research/Parametric-Contrastive-Learning#16]
Great work! Looking forward to the code for segmentation. When will it be released?

**Comment by jiequancui** [comment]
Hi, 

Thanks for your interest in our work. The code can be released in one month. 

Best,

**Comment by yyliu01** [comment]
Hi @jiequancui, 

I've waited for your code for a while. May I kindly ask if there is any plan to release it?

**Comment by xiaollu** [comment]
Hi! Thanks for your great work!  Just wondering when will the code for Region Rebalance will be released?

**Comment by jiequancui** [comment]
Hi,

Thanks for your interest in our work.

Our new version of the paper is submitted to CVPR.  The code will be released later.

Best,

**Comment by jiequancui** [comment]
code for RR & CeCo is released at https://github.com/dvlab-research/Parametric-Contrastive-Learning/blob/main/GPaCo/Seg/mmseg/models/decode_heads/uper_head_ceco.py
