### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_model/moco_ckpt.best.pth.tar' raise ProcessRaisedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaisedException: 

### ISSUE THREAD

**Issue by noreenanwar** [dvlab-research/Parametric-Contrastive-Learning#19]
Hi, Thank you so much for your work. I am facing this issue while using this repo. I don't know where to upload this file because this folder is not there.

**Comment by jiequancui** [comment]
Hi,

Thanks for your interest in our work.
Please download the pre-trained model at https://github.com/facebookresearch/mae.

Best,
