### ISSUE TITLE
Question about CIFAR-LT experiment

### ISSUE THREAD

**Issue by caisarl76** [dvlab-research/Parametric-Contrastive-Learning#5]
Hi! thank you for your interesting work!

I have a question on hyperparameters in CIFAR-LT dataset experiments

The paper explains alpha and moco temperature, but there is no explanation for the rest of the hyper-parameters(beta, gamma, augmentation stradegy). Can you please provide it?

**Comment by jiequancui** [comment]
Hi, thank you for your questions.

We have updated our code. Training code and configurations for CIFAR-LT are provided now.

**Comment by jiequancui** [comment]
Hi,

There seems something wrong with the current cifar configuration. We are working on it now. I will update it later.

**Comment by jiequancui** [comment]
Hi,

We have updated the training code and configurations for CIFAR-LT.

**Comment by Yancy10-1** [comment]
> Hi,
> 
> We have updated the training code and configurations for CIFAR-LT.

Hi, CIFAR-LT experiment is so interesting. Is the experiment  CIFAR-100 LT with imbalance factor 100 mentioned in the paper?  Does the project provide full CIFAR-100 experiment?

**Comment by jiequancui** [comment]
Hi,

The code on full CIFAR-100 for GPaCo will be released soon

**Comment by jiequancui** [comment]
Hi,

The training scripts on full CIFAR-100 for GPaCo are released.  Scripts on CIFAR-LT will be released later.
