### ISSUE TITLE
About Batch Size

### ISSUE THREAD

**Issue by oldfemalepig** [dvlab-research/Parametric-Contrastive-Learning#6]
Thank you very much for your work. I am currently trying to reproduce this work, and found that when the Batch Size is 128, the speed is relatively slow, and I want to increase the Batch Size to speed up training. But it is found that Batch Size is limited by the parameter MoCo-k, can I modify MoCo-k arbitrarily, will this affect the result?
Looking forward to your reply.

**Comment by jiequancui** [comment]
Hi,
Thanks for your questions.
The length of the queue can influence the converge value of the paco loss. A much smaller MoCo-k will degrade the performance.

If you have more GPU resources to speed up training,  32 images per GPU is recommended.
