### ISSUE TITLE
About the results of SupCon

### ISSUE THREAD

**Issue by tzhxs** [dvlab-research/Parametric-Contrastive-Learning#7]
Hi, I notice that compared with the FCL (which is similar to SupCon) in "EXPLORING BALANCED FEATURE SPACES FOR REPRESENTATION LEARNING", the result of SupCon given in your paper is much lower. What is the reason?

**Comment by jiequancui** [comment]
Hi, thank you for your question!

I'm not sure the detailed reason now. Maybe I will study it later. 
Before that,  I think you can try the SupCon by slightly updating our code.
