### ISSUE TITLE
Where to download the pretrained model?

### ISSUE THREAD

**Issue by hongxin001** [dvlab-research/Parametric-Contrastive-Learning#8]
Hi,

Thanks for your work. I found that there is a requirement for pretrained_models/resnet152-394f9c45.pth when I run the PlacesLT_train_R152.sh. Could you share the link to download the pretrained model?

Best Regards,
Hongxin

**Comment by jiequancui** [comment]
Hi Hongxin,

We just use the pre-trained model from the torchvision. You can find the model with this official link "https://download.pytorch.org/models/resnet152-394f9c45.pth".

Best,
Jiequan
